### ISSUE TITLE
bug submit

### ISSUE THREAD

**Issue by jiangyi0923** [Artenuvielle/GW2-SCT#17]
Since I am a Chinese server, I made a program to get all the skill pictures, and made the skill.ini file and translated lang.ini

Two bugs were found in use

1. Tooltip does not display Chinese properly. The character will change to "?"

2. Can't end the game normally, the game program has no response for a long time, so it can only be forced to end it, and there is no file found in the "icons" folder that has been downloaded,and sct.log is not have log

this is my  configuration file
[sct.zip](https://github.com/Artenuvielle/GW2-SCT/files/5277794/sct.zip)

**Comment by jiangyi0923** [comment]
Does the program still download icon files after generating the skill.ini file?
This does not seem reasonable,
If you get the skill json file through the wiki website api, it is very unrealistic in China, because it has a size of 3.5M, it will unpredictably disconnect the download link and cause the game to be ended. If you can, I still hope you can localize  Optimization

**Comment by Artenuvielle** [comment]
The current implementation still requires calls to the GW2 API even when you have predownloaded files for skill icons. The reason for that was to only load textures from icon directory which should be required by the game and not just any file in the directory. Therefor I first check all skills listed in the api (https://api.guildwars2.com/v2/skills). However, I found that any bad request (any HTTP response code except 2xx) would result in the game crashing and this *should* be fixed in upcoming 1.3-RC4.

Concerning your second problem, I opened a new ticket (https://github.com/Artenuvielle/GW2-SCT/issues/23) about this.
