### ISSUE TITLE
Support for d912pxy

### ISSUE THREAD

**Issue by evilandrex** [Artenuvielle/GW2-SCT#5]
Can SCT be made to work with this? https://github.com/megai2/d912pxy/issues/38

**Comment by Artenuvielle** [comment]
As long as there is compatibility with ArcDPS (which currentliy should be there due to chainloading), also SCT should be compatible.

**Comment by WanYaa** [comment]
the skill icons feature of SCT is not working with a chainloaded d912pxy otherwise its working
https://github.com/megai2/d912pxy/issues/13#issuecomment-460787441
the crash does not occur anymore in recent release of d912pxy
but skill icons from SCT are not loaded either as long as arc chainloads d912pxy

**Comment by Artenuvielle** [comment]
For loading the skill icons and showing them I use DirectX function D3DXCreateTextureFromFileInMemory. Maybe I have to get in touch with the developer of d912 later.

**Comment by paroyer** [comment]
Personally it works with out skill icons, tho with them as soon as more then 3 try to be displayed at the same time it crashes

**Comment by evilandrex** [comment]
I'm happy that this is isn't crashing me again but I would love for the skill icons to come back too!

**Comment by Artenuvielle** [comment]
Version 1.2-RC3 should now support d912pxy
