### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by livarkhal** [Artenuvielle/GW2-SCT#8]
Hi :)

I wan't to try this tool but it don't work corectly .....
My damage appears to be the heal Oo 

This tool is it maintained? or is it dead?

**Comment by Artenuvielle** [comment]
Numerous people reached out to me about the issue of showing outgoing damage as incoming and vice versa. This was due to a change in the arcdps API and I'm working since yesterday on an update including some features I allready prepared quite some time ago, including: skill filter lists, translation support and chinese font support.

**Comment by Artenuvielle** [comment]
This was fixed with version 1.2RC-1
